### ISSUE TITLE
JUnit Failures

### ISSUE THREAD

**Issue by niklaspolke** [mkymikky/DupFinder#15]
JUnit Failures under Windows 7:

getValidStreamWithValidFile(de.b0n.dir.processor.FileStreamTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<-1> but was:<46>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at de.b0n.dir.processor.FileStreamTest.getValidStreamWithValidFile(FileStreamTest.java:75)

getValidFileWithValidFile(de.b0n.dir.processor.FileStreamTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: wrong file size expected:<91> but was:<94>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at de.b0n.dir.processor.FileStreamTest.getValidFileWithValidFile(FileStreamTest.java:83)

**Comment by niklaspolke** [comment]
Doch kein Fehler - das Problem ist, wenn die **GIT** die folgende Einstellung unter Windows verwendet:
`core.autocrlf=false`

Dann macht Windows aus LF das Windows-typische CRLF und beim Commit/Push wieder umgekehrt aus CRLF -> LF. Dadurch war die Datei bei mir größer.

Trotzdem finde ich es unschön, wenn der Test so anfällig ist. Ggf. wäre es möglich, diese Datei erst während des Testlaufs zu erstellen oder 94 wie auch 91 als Ergebnis zu akzeptieren?

**Comment by mkymikky** [comment]
Zwei Ergebnisse zu akzeptieren finde ich falsch, das lässt Raum für Fehler und ist auch nicht ganz so gut zu implementieren.
Lieber würde ich die Testdaten dynamisch erzeugen.

**Comment by mkymikky** [comment]
Fixed
